openapi: 3.0.3
info:
  title: Auth-System
  description: Sistema de criação de contas e autenticação
  version: 1.0.0
tags:
  - name: Autenticação
servers:
  - url: http://localhost:8080/
paths:
  /v1/authentication/login:
    post:
      tags:
        - Efetuar login
      operationId: login
      summary: 'Realiza o login'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginPresentation'
        required: true
      responses:
        '201':
          description: Cadastrado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginRepresentation'
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErroListPresentation'
        '422':
          description: Erros de negócio
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErroNegocioPresentation'
        '500':
          description: Ocorreu um erro interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErroPresentation'
components:
  schemas:
    LoginPresentation:
      type: object
      required:
        - email
        - senha
      properties:
        email:
          type: string
          example: "loremIpsum@gmail.com"
          minLength: 5
          maxLength: 255
          pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
        senha:
          type: string
          example: "secret"
          minLength: 5
          maxLength: 255
          pattern: '[^<>!;\/\\]+$'

    LoginRepresentation:
      type: object
      properties:
        token:
          type: string
        expiresIn:
          type: integer
          format: int64

    ErroListPresentation:
      type: object
      properties:
        code:
          type: integer
          example: 400
        correlationError:
          type: string
          example: "Bad Request"
        errors:
          type: array
          items:
            type: string

    ErroNegocioPresentation:
      type: object
      properties:
        enumError:
          type: string
          example: "ERRO_UNPROCESSABLE_ENTITY"
        message:
          type: string
          example: "Unprocessable Entity"

    ErroPresentation:
      type: object
      properties:
        code:
          type: integer
          example: 500
        message:
          type: string
          example: "Erro de validacao"
        correlationError:
          type: string
          example: "ERRO_PARAMETROS_INVALIDOS"